version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-github
    schedule:
      interval: 'daily'
    groups:
      navikt:
        patterns:
          - '@navikt/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-plugin-*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
