apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: hag-dokument-proxy
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{ image }}
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  ingresses:
    - https://hag-dokument-proxy.ekstern.dev.nav.no
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: sykepenger-im-lps-api
          namespace: helsearbeidsgiver
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  observability:
    logging:
      destinations:
        - id: loki
  env:
      AUDIENCE: 'dev-gcp:helsearbeidsgiver:sykepenger-im-lps-api'
      API_BASEPATH: 'http://sykepenger-im-lps-api/intern/personbruker/'